---
title: "2019 TTW R Workshop"
output: 
        github_document:
                toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This page is the central hub of materials for the R training that will be held at the SWMP Technician Training Workshop on March 15, 2019.  

# Things to have on your computer before the workshop:

## Software  

You need to install R first, then RStudio. **You may need a system administrator for installation**, so do this early!

### R, v. 3.5.2 or higher  

Download from [CRAN](https://cran.r-project.org/) for any operating system.

### RStudio, v. 1.1.463 or higher  

Download the free Desktop version from [RStudio](https://www.rstudio.com/products/rstudio/download/) for any operating system.


## Some zip file of instructional scripts etc.  

host on Kim's google drive?

### Packages  

Run `00a_package_installation.R`  

Followed by `00b_package_check.R` to make sure all packages installed properly

## Reserve-specific data  

### Status Report package

Link to google drive? Where do these live for reserves?  

### Raw sonde and/or MET files  

Choose your own adventure on this - bring files straight off the EXOs, and bring a handful of WQ and MET files that have been emailed back to you when you upload data to the CDMO.